### ISSUE TITLE
Binding ViewControllers

### ISSUE THREAD

**Issue by affederaffe** [Auros/SiraUtil#10]
Hey Auros, found a new bug regarding UI:
1. When binding a ViewController with "Container.BindViewController", it isn't curved correctly if it's shown on the left/right (already discussed in #pc-mod-dev)
2. When binfing a ViewController with "Container.Bind<>().FromNewComponentAsViewController()" it'll be curved correctly but won't be bound again on an app restart, for example when you hit apply in mod settings, resulting in NullReferenceExceptions.

**Comment by Auros** [comment]
I have already deprecated BindViewConteoller for a while and the next update will now mark it as obsolete. Your second issue is literally impossible unless you're using a persistent singleton or DontDestroyOnLoad somewhere in your code.

**Comment by affederaffe** [comment]
I indeed used DontDestroyOnLoad. For the next update, you might want to update the readme then. Even though, thanks for the help and for making SiraUtil in general!
