### ISSUE TITLE
How do i install this?

### ISSUE THREAD

**Issue by Los-3r** [Auros/SiraUtil#16]
How do i install this? Where do i drag it into?

**Comment by Auros** [comment]
I recommend you download it through [Mod Assistant](https://github.com/Assistant/ModAssistant/).

**Comment by Los-3r** [comment]
am i able to download it through [BSMI/BSMM](https://github.com/Umbranoxio/BeatSaberModInstaller) ?

**Comment by Auros** [comment]
No.

**Comment by Los-3r** [comment]
Ok, how do i install Mod Assistant if my beat saber installation is on my quest?

**Comment by Auros** [comment]
Resolved in [ModAssistant#351](https://github.com/Assistant/ModAssistant/issues/351)
