### ISSUE TITLE
Camera smoothing disabled in Scoresaber replays

### ISSUE THREAD

**Issue by DonTrolav** [Auros/SiraUtil#3]
When enabling FPFCToggle, Scoresaber replays will show exact headset position and rotation rather than smoothing them.
Also, camera pivot point will be screwed after exiting the replay.

**Comment by Auros** [comment]
> Scoresaber replays will show exact headset position and rotation rather than smoothing them
This is not a problem with FPFCToggle. The 1.12.2 version of CameraPlus disables itself if it detects the FPFC launch argument, so it won't provide smoothing.
> Also, camera pivot point will be screwed after exiting the replay.
I have fixed this internally and will be releasing the update soon.
