### ISSUE TITLE
More descriptive logging for Affinity

### ISSUE THREAD

**Issue by Aeroluna** [Auros/SiraUtil#40]
Would make debugging Affinity patches easier by providing the Harmony user, and the patch class.
Example log of a failed Harmony patch: [_latest.log](https://github.com/Auros/SiraUtil/files/8305230/_latest.log)

**Comment by nicoco007** [comment]
Addressed in 8ee9c5155ef23d15bc3a297b86c28e701085ac4b. You should now get a line in the stack trace that says `Rethrow as AffinityException` with the method details.
