### ISSUE TITLE
Swings become square when using SiraUtil Fpfc

### ISSUE THREAD

**Issue by SyncBS** [Auros/SiraUtil#45]
Swings become mostly squared when SiraUtil Fpfc Launch Option.

https://www.youtube.com/watch?v=0yJE9bh-djE
Video: First with SiraUtil fpfc and after without it (normal gameplay)
I recommend looking at bottom right camera to notice how much it changes.
[_latest.log](https://github.com/Auros/SiraUtil/files/8438970/_latest.log)

Logs from viewing a replay with SiraUtil Fpfc Launch Option.
This is also the case while playing with Fpfc Toggle ignored in SiraUtils, the swings will be squared while playing ingame.

SiraUtils itself has FPFCToggle "Ignore": true, but same happens with it false.

**Comment by SyncBS** [comment]
https://clips.twitch.tv/TangibleBloodyMomSuperVinlin-k3degQyJxY8cEySt

Clip of it happening for the first time ingame.

**Comment by Auros** [comment]
Does this happen in the headset or just in cameras? You can test this by going to a V2 replay and changing the location to Left or Right with the in headset UI (double click one of your controller's triggers)

**Comment by SyncBS** [comment]
It happens in the headset itself even if it's not a replay (the clip I sent it was happening in Saber Factory's menu). 

When it comes to replays it happens to every V2 Replay (have not tried to look at a V1 replay) and it is on both things, headset and cameras.

**Comment by Auros** [comment]
This isn't an issue with SiraUtil. It is an issue with SaberFactory (keep in mind, FPFC is a feature in the base game that other mods listen on).

After some testing, this only occurs when using a custom saber with SaberFactory installed. It doesn't happen for base game sabers nor custom sabers.

If I had to guess the issue, it's specifically this line [here](https://github.com/ToniMacaroni/SaberFactory/blob/05491a6af22a697d30273d715262b5a9599ef1a1/SaberFactory/Installers/PluginAppInstaller.cs#L47) which explicitly caps the framerate of trails when FPFC is in the launch argument.

Gonna close this issue for now, I recommend you bring its attention to @ToniMacaroni over at the [Saber Factory repo](https://github.com/ToniMacaroni/SaberFactory/issues/new) (or if Toni takes a look at this issue instead)

**Comment by Auros** [comment]
👍 

![image](https://user-images.githubusercontent.com/41306347/162585172-b925511e-291c-422e-ad27-141988fbef72.png)

**Comment by SyncBS** [comment]
Thank you for letting me know, appreciate the patience to review the issue.
