### ISSUE TITLE
SiraUtil FPFC not looking through pointer

### ISSUE THREAD

**Issue by SyncBS** [Auros/SiraUtil#46]
FPFC looks as if it has first person pivot disabled (it's enabled in camera2) in game version 1.21 and 1.22

https://streamable.com/vufl49
![image](https://user-images.githubusercontent.com/86927709/167122101-88ca3fd5-0c79-46bf-a937-dc0a4fff1b0b.png)

**Comment by Auros** [comment]
![image](https://user-images.githubusercontent.com/41306347/167236606-43d7789d-3787-4bda-910d-135686b6a09e.png)
According to Kinsi this has been fixed.

**Comment by kinsi55** [comment]
Fixed in next Cam2 update https://github.com/kinsi55/CS_BeatSaber_Camera2/commit/742c8edc9bd311e3ed716ec5a2712eed72b8b928

**Comment by Auros** [comment]
Thanks Kinsi
