### ISSUE TITLE
Make installing logging more descriptive

### ISSUE THREAD

**Issue by Aeroluna** [Auros/SiraUtil#52]
Change `.Name` in [this line](https://github.com/Auros/SiraUtil/blob/main/SiraUtil/Zenject/ZenjectManager.cs#L93) to use `.FullName` to make it easier to debug when mods use generic names like "GameInstaller"

![image](https://user-images.githubusercontent.com/40481393/185629240-97dec479-5826-4702-96d1-1c9c057b866f.png)

**Comment by Auros** [comment]
Added in SiraUtil 3.1.2
