### ISSUE TITLE
Song Selection Scrolling Issue

### ISSUE THREAD

**Issue by pandaman09** [Auros/SiraUtil#6]
I've noticed that installing this mod with ModAssistant causes the menu to scroll up infinity.

Here's how I was able to recreate the issue.

1. Fresh Install of Beat Saber v.1.13.0
2. Install BISPA v4.1.3
3. Launch Beat Saber, confirmed no issue present,
4. Install SiraUtil v2.2.0
5. Launch Beat Saber, issue now present in song selection screen.

Let me know if you need any more information.

**Comment by Auros** [comment]
Is this the only mod installed? So in your Plugins folder, the only file(s) inside there are SiraUtil.dll and SiraUtil.xml?

**Comment by pandaman09** [comment]
That is correct. I also just confirmed this is happening on SiraUtil v2.1.0

**Comment by Auros** [comment]
Can you upload your log file (located in Logs/_latest.log)

**Comment by pandaman09** [comment]
[2020.11.29.18.29.18.log](https://github.com/Auros/SiraUtil/files/5613155/2020.11.29.18.29.18.log)
Log Attached. Would you like me to get a log for v2.1.0 also?

**Comment by Auros** [comment]
Could you inform me about your system environment?
What headset do you use and what store platform?
Examples: (Valve Index on Steam), (Valve Index with Vive Wands on Steam), (Oculus Rift on Steam with vrmode oculus), (Oculus CV1 on Oculus Store), etc

**Comment by pandaman09** [comment]
Windows 10 x64 Build 19041, I use Steam and and Valve Index with Knuckles controllers.

**Comment by Auros** [comment]
In your order of testing, you said you did a fresh install and then installed BSIPA. Did you launch the game before you installed BSIPA?

**Comment by pandaman09** [comment]
I did not launch the game before installing BIPSA, but I will do so now to confirm it still occurs.

**Comment by Auros** [comment]
I'd also like to make sure that removing SiraUtil restores natural scrolling. And if you can install a bunch of mods but delete SiraUtil if the issue is still present. I'm still skeptical whether or not this is SiraUtil since I don't ever dip into any sort of system or code that would mess up scrolling. And, on its own with the default config, SiraUtil does *almost* nothing (does a tiny thing in the game scene but that's it).

**Comment by pandaman09** [comment]
It looks like it's unrelated to SiraUtil.

It appeared and disappeared when I installed and uninstalled SiraUtil with other mods installed. At first I thought it was related to CameraPlus and SiraUtil together, because after I installed CameraPlus the issue started happening. I went back through my list uninstalling mods and the issue stopped after I remove SiraUtil. I did a fresh install as noted previously, and started to install things one at a time. The issue didn't present itself until the 2nd launch after SiraUtil was installed.

Now I installed beat saber fresh, launching it for the first time without any mods installed and it occurred again. This seems to be a Beat Saber bug, or something related to my setup, that coincidentally showed up after installing SiraUtil. Two times.

**Comment by Auros** [comment]
Some other people have come across this issue as of lately and there's a small mod which just removes all controller scrolling. If you want it, you can get it [here](https://cdn.discordapp.com/attachments/473348528417275905/771279486935105546/ScrollNullity.dll)
